name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: g++ -pthread -O2 -o cm_sokoban.elf *.cc 
      run: g++ -pthread -O2 -o cm_sokoban.elf *.cc
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: cm_sokoban.elf
        path: cm_sokoban.elf
